### ISSUE TITLE
react-fluid-table: shrinking long column headers

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1681]
When filtering column's and then clearing the filters some of the longer column headers would shrink causing the width to be smaller than intended.

Bug has been fixed by adding a css style to adjust the column's width to be handled automatically.

```css
.row-wrapper {
  width: auto !important;
}
```
