### ISSUE TITLE
Docusaurus Next Steps

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1719]

**Comment by meissadia** [comment]
## It's been bothering me...
that it's so difficult to tell which sidebar item a user has selected.  This was one thing that felt like a stark difference between the SBL FIG (where it's hyper-obvious) and our DS site.  I've been experimenting, what do folks think of these changes?
 
## Changes
On the left sidebar we've got different highlights for submenus vs items. Submenus are `bold + underline` while items are `bold + left border`.  
  
On the right sidebar we mirror the submenu styles with the bold + underline, which helps the selection stand out amongst it's peers without taking up additional horizontal space. 
 
## Screenshots
 
 |Before|After|
 |---|---|
|<img width="1473" alt="DS-sidebard-before" src="https://user-images.githubusercontent.com/2592907/221029434-ba2dd2db-e00e-497f-b0b5-5ecd7b9ef1dc.png">|<img width="1474" alt="DS-sidebard-after" src="https://user-images.githubusercontent.com/2592907/221029484-28ea0a92-556b-413f-adce-9215d973ad68.png">|

## Code
In `custom.css`:
```css

.menu__link--active {
  border-radius: 0;
  font-weight: bold;
  border-left: 5px solid #1f498f;
}

.menu__link--sublist.menu__link--active,
.table-of-contents__link--active {
  font-weight:bold;
  border-left: none;
  text-decoration: underline;
}
```
